server:
  port: 8082
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.26.130:9092,192.168.26.130:9093,192.168.26.130:9094
      batchSize: 10
      compressionType: snappy
      acks: all
    consumer:
      group-id: group3
      bootstrap-servers: 192.168.26.130:9092,192.168.26.130:9093,192.168.26.130:9094
#      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
#    bootstrap-servers: 192.168.26.130:9092,192.168.26.130:9093,192.168.26.130:9094
