
server:
  port: 8083
spring:
  kafka:
    consumer:
      group-id: group2
      bootstrap-servers: 192.168.26.130:9092,192.168.26.130:9093,192.168.26.130:9094
#      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
#    bootstrap-servers: 192.168.26.130:9092,192.168.26.130:9093,192.168.26.130:9094
